repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: no-commit-to-branch
        args: ['--branch', 'master']
    -   id: pretty-format-json
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: uncrustify
-   repo: https://github.com/gherynos/pre-commit-java
    rev: v0.1.0  # Use the ref you want to point at
    hooks:
      - id: checkstyle
        args: [--diff, --check]

