repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: no-commit-to-branch
        name: Don't push to main branch
        args: ['--branch', 'main']
        stages: [push]

    -   id: pretty-format-json
      #-   repo: https://github.com/pocc/pre-commit-hooks
      # rev: master
      # hooks:
      # - id: uncrustify'''
-   repo: local
    hooks:
    -   id: jira-ticket
        name: check for jira ticket
        language: pygrep
        entry: '\A(?![A-Z]+-[0-9]+)'
        args: [--multiline]
        stages: [commit-msg]
